[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Cthulhu = "f68482b8-f384-11e8-15f7-abe071a5a75f"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
MethodAnalysis = "85b6ec6f-f7df-4429-9514-a64bcd9ee824"
SnoopCompile = "aa65fe97-06da-5843-b5b1-d5d13cad87d2"

[compat]
AbstractTrees = "0.3"
JET = "0.4"
MethodAnalysis = "0.4"
SnoopCompile = "2.6"
