[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Cthulhu = "f68482b8-f384-11e8-15f7-abe071a5a75f"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
JETTest = "a79fb612-4a80-4749-a9bd-c2faab13da61"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
MethodAnalysis = "85b6ec6f-f7df-4429-9514-a64bcd9ee824"
ProfileSVG = "132c30aa-f267-4189-9183-c8a63c7e05e6"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SnoopCompile = "aa65fe97-06da-5843-b5b1-d5d13cad87d2"

[compat]
AbstractTrees = "0.3"
BenchmarkTools = "1"
Cthulhu = "2.1"
Flux = "0.12"
JET = "0.4.5"
JETTest = "0.1"
MacroTools = "0.5.6"
MethodAnalysis = "0.4"
ProfileSVG = "0.2"
ProfileView = "0.6.10"
PyPlot = "2.9"
SnoopCompile = "2.7"
